spring:
  application:
    name: quiz-server
  datasource:
    url: jdbc:h2:mem:answers
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  file: logs/grpc-quiz-server.log
server:
  port: 8090

grpc:
  server:
    port: 8091
  deadline: 60